name: CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
        architecture: 'x64' 

    - name: Display Python version
      run: python myscript.py


