name: Script Tester

on:
  schedule:
  - cron: "*/5 * * * *"

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' 
        architecture: 'x64' 
    - run: ls
    - run: python myscript.py


